### ISSUE TITLE
Example has extra slash

### ISSUE THREAD

**Issue by doublejosh** [timdp/metalsmith-discover-partials#7]
I couldn't get this plugin working until I noticed the extra slash in the regex pattern 🙀 

```
{
  "directory": "partials",
  "pattern": "/\.hbs$/"
}
```

**Comment by timdp** [comment]
You mean the backslash? That's not a typo. It's escaping the backslash so the regexp compiler turns it into an actual dot rather than the metacharacter that will match any character. Without it, it will also match e.g. `file.xxxhbs`, as the dot will also match `x`.

**Comment by doublejosh** [comment]
Strange, the example did not work as-is for me.  Thanks for the explanation.
